### ISSUE TITLE
jẹ́kí should not be use with increments 

### ISSUE THREAD

**Issue by skyusuf15** [anoniscoding/yorlang#58]
Since `jẹ́kí` is use for creating variables it makes no sense using it to increment for example `fún ( jẹ́kí i = 0 ; i < 5 ; jẹ́kí i = i + 1 ;)   {}`, ` jẹ́kí i = i + 1` should be `i = i + 1` since variable `i` as been created, no point creating it again and I don’t see any reason why we should use a keyword to assign values to variables

**Comment by anoniscoding** [comment]
Thank you for your input. The purpose of yorlang is to allow beginners to interact with programming concepts and syntax in their native tongue.

So the idea of ```jeki``` in yorlang is that it should be used whenever you are initializing and re-assigning a variable so that what is going on is clear to a beginner.

More or less we are allowing the beginner to let i be 0 and later when he is incrementing it, the beginner is still aware syntatically that he is simply letting a be 1.

It's the same reason why i++ and i-- are not supported. I'm only trying to make things as clear as possible.

We should also remember that yorlang is not a commercial language. It just a stepping stone to helping them get familiar with programming concept and syntax in the language they understand. 

**They must still learn the commercial languages that you and I know**

**Comment by anoniscoding** [comment]
Another thing to note, using jeki when re-assigning a variable does not recreate the variable, it simply updates its value in memory.
Following my php analogy, $a = 1; changing it to $a = 2; will not recreate the variable $a. It will simply update its value and the same applies in yorlang
